"""
Inference logic for the LeafVision app.

This mirrors load_and_prep() / predict_single() from the research repo's
eval_utils.py exactly, on purpose: the whole point of the research is that
preprocessing consistency is what makes results trustworthy. The app should
not diverge from the pipeline that was actually evaluated.
"""

from pathlib import Path
import json

import numpy as np
import cv2
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.models import load_model

IMG_SIZE = (128, 128)


def load_class_map(class_map_path):
    """Load the idx -> class_name mapping generated by generate_class_map.py."""
    with open(class_map_path) as f:
        raw = json.load(f)
    return {int(k): v for k, v in raw.items()}


def load_leafvision_model(model_path):
    """Load the trained .keras model once at app startup."""
    return load_model(model_path)


def load_and_prep(img_bgr, size=IMG_SIZE):
    """Identical to eval_utils.load_and_prep: BGR->RGB, resize, batch, EfficientNet preprocess."""
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, size)
    batch = np.expand_dims(img_resized.astype(np.float32), axis=0)
    return preprocess_input(batch)


def predict(model, img_bgr, idx_to_class, size=IMG_SIZE):
    """
    Run one image through the model.
    Returns a list of {label, confidence} dicts, sorted by confidence
    descending, so the UI can show the full distribution, not just the
    top guess.
    """
    batch = load_and_prep(img_bgr, size)
    probs = model.predict(batch, verbose=0)[0]

    results = [
        {"label": idx_to_class[i], "confidence": round(float(p) * 100, 1)}
        for i, p in enumerate(probs)
    ]
    results.sort(key=lambda r: r["confidence"], reverse=True)
    return results
